name: StripTHeText - Frontend

channels:
  - defaults

dependencies:
  - python=3.11.0
  - pip
  - pip:
    - streamlit
    - streamlit-audiorecorder
    - pyperclip
    - pandas
    - numpy
    - scikit-learn
    - nltk
    - tensorflow
    - torch
    - transformers
    - datasets
    - huggingface
    - openai-whisper
    - pyperclip
    - python-docx