name: StripTheText_Backend

channels:
  - defaults

dependencies:
  - python=3.11.0
  - pip
  - pip:
      - asyncio
      - uvicorn
      - pandas
      - fastapi
      - python-dotenv
      - tensorflow
      - transformers
      - pydantic
      - websockets
      - numpy
      - openai-whisper
