name: StripTHeText - Frontend

channels:
  - defaults

dependencies:
  - python=3.11.0
  - pip
  - pip:
    - streamlit
    - streamlit-audiorecorder
    - pyperclip
    - python-docx
    - openai-whisper
